name: tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  schedule:
    - cron: '0 0 10 * *'

jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0]
        composer-flag: [prefer-lowest, prefer-stable]

    name: php v${{ matrix.php }} - ${{ matrix.composer-flag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo
          tools: composer:v2
          coverage: pcov

      - name: Install dependencies
        run: composer update --${{ matrix.composer-flag }} --no-interaction --no-progress

      - name: Execute tests
        run: composer test -- --coverage-clover=coverage.xml

      - name: Submit code coverage
        run: bash <(curl -s https://codecov.io/bash)
